EXE = straight_insertion_sort binary_insertion_sort bubble_sort quick_sort select_sort heap_sort merge_sort radix_sort

straight_insertion_sort:
	gcc straight_insertion_sort.c \
	-o straight_insertion_sort

binary_insertion_sort:
	gcc binary_insertion_sort.c \
	-o binary_insertion_sort

bubble_sort:
	gcc bubble_sort.c \
	-o bubble_sort

quick_sort:
	gcc quick_sort.c \
	-o quick_sort

select_sort:
	gcc select_sort.c \
	-o select_sort

heap_sort:
	gcc heap_sort.c \
	-o heap_sort

merge_sort:
	gcc merge_sort.c \
	-o merge_sort

radix_sort:
	gcc radix_sort.c \
	-o radix_sort

clean:
	rm -rf ${EXE}

all: ${EXE}