EXE = straight_insertion_sort binary_insertion_sort

straight_insertion_sort:
	gcc straight_insertion_sort.c \
	-o straight_insertion_sort

binary_insertion_sort:
	gcc binary_insertion_sort.c \
	-o binary_insertion_sort

clean:
	rm -rf ${EXE}

all: ${EXE}